"""add diversity_metric unique constraint

Revision ID: 23d6781e645f
Revises: b938a95dd8d4
Create Date: 2026-07-12 15:23:10.725443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add diversity_metric unique constraint

Revision ID: 23d6781e645f
Revises: b938a95dd8d4
Create Date: 2026-07-12 15:23:10.725443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d6781e645f'
down_revision: Union[str, Sequence[str], None] = 'b938a95dd8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_dept_period', 'diversity_metrics', ['department_id', 'period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_dept_period', 'diversity_metrics', type_='unique')
    # ### end Alembic commands ###
