"""add diversity_metric unique constraint

Revision ID: 23d6781e645f
Revises: b938a95dd8d4
Create Date: 2026-07-12 15:23:10.725443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d6781e645f'
down_revision: Union[str, Sequence[str], None] = 'b938a95dd8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carbon_transactions', 'emission_factor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('fk_department_head_user_id', 'departments', 'users', ['head_user_id'], ['id'], use_alter=True)
    op.create_unique_constraint('uix_dept_period', 'diversity_metrics', ['department_id', 'period'])
    op.create_foreign_key('fk_user_department_id', 'users', 'departments', ['department_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_department_id', 'users', type_='foreignkey')
    op.drop_constraint('uix_dept_period', 'diversity_metrics', type_='unique')
    op.drop_constraint('fk_department_head_user_id', 'departments', type_='foreignkey')
    op.alter_column('carbon_transactions', 'emission_factor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
