"""Add audit status and notification prefs

Revision ID: 4cc2aca17ce2
Revises: 1f6cc860cb48
Create Date: 2026-07-12 15:57:19.816260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc2aca17ce2'
down_revision: Union[str, Sequence[str], None] = '1f6cc860cb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first for PostgreSQL
    auditstatus = sa.Enum('under_review', 'completed', name='auditstatus')
    auditstatus.create(op.get_bind(), checkfirst=True)
    
    op.add_column('audits', sa.Column('status', auditstatus, nullable=True))
    op.execute("UPDATE audits SET status = 'under_review'")
    op.alter_column('audits', 'status', nullable=False)
    
    op.add_column('settings', sa.Column('notification_prefs', sa.JSON(), nullable=True))
    op.execute("UPDATE settings SET notification_prefs = '{}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'notification_prefs')
    op.drop_column('audits', 'status')
    # ### end Alembic commands ###
